### ISSUE TITLE
Add block storage, transaction storage

### ISSUE THREAD

**Issue by Kangmo** [ScaleChain/scalachain#10]
### Add block storage
1. Feature : Store blocks in fixed size block files, and each block file has the on-the-wire format of blocks. 
2. Feature : Search blocks by block hash 
3. Feature : Store blockheaders separately, to implement initial block download steps with headers-first apporach.
4. Feature : The block storage should be persistent.
5. Feature : Search blocks by transaction hash
6. Feature : Search UTXO by address.
### Add transaction storage.
1. Feature : Store transactions in memory, and each transaction should be searchable by the transaction hash.
2. Feature : Search blocks by transaction hash
3. Feature : Search UTXO by address.
### Transaction Reader.

Looking up the block storage and transaction storage, transaction reader should be able to :
1. Feature : Search blocks by transaction hash, 
2. Feature : Search UTXO by address, 
## Why

To manage blocks and transactions, we need these modules.
### Add block storage

Implement block storage that stores blocks on multiple fixed size block files. 
Each block file is implemented using random access file and file channel.
The block storage uses bitcoin protocol encoder to encode/decode blockheader/block/transaction data.
### Add transaction storage.

Use HashMap to store transactions by hash.
### Transaction Reader.

Transaction Reader uses block storage and transaction storage to implement features.

**Comment by Kangmo** [comment]
## Done : Implemented block header, block, transaction storage.
- Block header and block storage use on-disk data files.
- These are implemented as record based data files, and also support indexing on these records using libraries like levelDB( to be done).
- Transaction storage is transient, so it is stored in-memory.

**Comment by wolfshtein** [comment]
too long to read :8ball: 

(edited)

**Comment by Kangmo** [comment]
In-Progress : Write test cases for block storage and transaction storage.
Why : Need to guarantee the quality of code.
How : Use scala-test.

**Comment by wolfshtein** [comment]
:1234:

**Comment by Kangmo** [comment]
Here is the list of data files and indexes for ScaleChain.

# Core blockchain

# Block files

A block file has multiple blocks in on-the-wire format. We maintain multiple block files.

# List of indexes

## store/search transaction by hash

### key : transaction hash

### value : record locator (on block file)

### event : put

Upon receival of blocks on top of the (current) longest blockchain.

### event : del

Never happens

### event : find

## store/search block by hash

### key : block hash

### value : record locator (on block file)

### event : put

Upon receival of blocks on top of the (current) longest blockchain.

### event : del

Never happens

### event : find

## list unspent coins by address

### key : address & transaction id & output index & coin amount

### value : empty

c.f. \* means an address will have multiple out-points per address.

### event : put

A new valid transaction which has an UTXO paying to the given address.

### event : del

The coin at a specific outpoint was spent.

### event : find

Find UTXOs by address.

# Wallet

# Account files

An account file has following account records. We can maintain 

## store/search account

### key : account name

### value : address*

### event : put

Upon the creation of a new account. A default receival address is created and attached.

### event : del

### event : find

# Database

Use rocksdb.

**Comment by wolfshtein** [comment]
:100: ?

**Comment by Kangmo** [comment]
Done using RocksDB. Code pushed. 

https://github.com/ScaleChain/scalechain/commit/1924a5bd197734035dce90b3c4648aa03f87f1ff
