### ISSUE TITLE
port scalechain-util from Scala to Kotlin

### ISSUE THREAD

**Issue by Kangmo** [ScaleChain/scalachain#108]
## What
port scalechain-util from Scala to Kotlin

## Why
Scala is hard to learn, Kotlin is not.

## How
Copy Scala code, modify the code to Kotlin.

**Comment by Kangmo** [comment]
Will bring this issue back when we decide to port to Kotlin.

**Comment by b0c1** [comment]
small NetUtils help ;)

``` kotlin
    val x:List<InetAddress> = Collections.list(NetworkInterface.getNetworkInterfaces())
      .flatMap { i-> Collections.list(i.getInetAddresses()) }
```

**Comment by Kangmo** [comment]
Thanks!!

2016년 11월 17일 목요일, Janos Habernotifications@github.com님이 작성한 메시지:

**Comment by Kangmo** [comment]
Done : Port scalechain-proto from Scala to Kotlin.

## How
- Use Type? instead of option type.
- Use native Java byte array when possible (for better performance)
- Use Java collection when possible.

## Why
- We will completely get rid of Scala code from scalechain.
- We will implement codec without using scodec, which is very very slow.

**Comment by Kangmo** [comment]
Done : Add test cases for classes in proto layer.

## Why

We need to meet 90% branch coverage with unit tests.

## How

Use kotlin test to automate test cases.

**Comment by Kangmo** [comment]
In-progress : Port test cases in scalechain-proto-codec 
Port test cases from Scala to Kotlin

## Why
- Need to have test cases before porting classes to make sure they work correctly.

## How
- Come up with interfaces for encoding and decoding a data class that implements ProtocolMessage
- Port test of the class to Kotlin
- Make sure the test passes
- Port test cases of rest of classes.

**Comment by Kangmo** [comment]
done
