### ISSUE TITLE
How to run multi nodes

### ISSUE THREAD

**Issue by ZhuYuJin** [ScaleChain/scalachain#109]
I can successfully run a single node using the original code.
But, after adding four additional addresses in config/scalachain.conf, run-multi.sh is failed. Did I miss some configurations?

**Comment by Kangmo** [comment]
Hi ZhuYuJin,

did you copy .env file?

The detailed description for running five nodes is here. Instead of running run-multi.sh, can you try steps in the following wiki?

https://github.com/ScaleChain/scalechain/wiki/How-to-start-a-ScaleChain-peer

In case you see any error, let me know. I will follow up ASAP today.

**Comment by ZhuYuJin** [comment]
1. I add another address in p2p.peers set

```
peers = [
      { address:"127.0.0.1", port:"7643" },
      { address:"127.0.0.1", port:"7644" }
    ]
```
1. sbt compile and modify .env and run ./run.sh 0 ./run.sh 1
2. node 0 says "15:12:35.261 [nioEventLoopGroup-43-1] INFO  i.s.b.net.p2p.RetryingConnector - Connection to 127.0.0.1:7644 failed."
   node1 shows port out of range
   <img width="560" alt="qq20161118-0 2x" src="https://cloud.githubusercontent.com/assets/5879410/20421853/a2500cb0-ada1-11e6-9609-3b8732595bb0.png">

I guess hosts.config should add one record "1 127.0.0.1 11002"
This solves the port out of range, but it still not work.
<img width="560" alt="qq20161118-1 2x" src="https://cloud.githubusercontent.com/assets/5879410/20421985/6f926696-ada2-11e6-85c3-2e735d64f57e.png">

**Comment by Kangmo** [comment]
The default configuration files work when you run five nodes. 
If you want to run two nodes, you need to change the following sections in the following files.

## config/hosts.config

```
#server id, address and port (the ids from 0 to n-1 are the service replicas)
0 127.0.0.1 11000
1 127.0.0.1 11001
7001 127.0.0.1 11100
```

## config/system.config

```
#Number of servers in the group
system.servers.num = 2

#Maximum number of faulty replicas
system.servers.f = 0

...

#Replicas ID for the initial view, separated by a comma.
# The number of replicas in this parameter should be equal to that specified in 'system.servers.num'
system.initial.view = 0,1

...

#This sets if the system will function in Byzantine or crash-only mode. Set to "true" to support Byzantine faults
system.bft = false

```

**Comment by ZhuYuJin** [comment]
It worked well! Thanks so much for your patience.
So does this blockchain support hot-plugging? When I shut down a node, the system stops the block mining.

**Comment by Kangmo** [comment]
No problem, ZhuYuJin, I thank for your patience. You nee to have at least three nodes up and running for mining. You can start and stop the fourth node.

**Comment by Kangmo** [comment]
@ZhuYuJin , thanks for your interest in this project. 
Currently the project is under heavy construction, but I will come up with a solid documentation on running multiple nodes.
#140 Write a documentation describing Multiple node execution

Also it will support hot plugging, I will make sure it works by the following work item.
#136 Write advanced functional tests

Closing this issue, but please feel free to reopen if you have any question, or feel free to comment to the above issues.

Again, thanks for your interest.
