### ISSUE TITLE
Draw Use Case Diagram for API(RPC) layer

### ISSUE THREAD

**Issue by Kangmo** [ScaleChain/scalachain#12]
## What

Draw use case diagrams for API(RPC) layer.
## Why
1. To summarize requirements of major modules.
2. To find out requirements of P2P layer, on which layer depends.
## How
1. Use StarUML for MacOS.
2. Draw each RPC feature as a use case. 
   https://bitcoin.org/en/developer-reference#rpc-quick-reference.
3. Draw sub use cases for each use case in the quick reference.

**Comment by nazimboudeffa** [comment]
i have never used blockchains before because it's look like not allowed in my country
:) <-<
btw, i follow this interesting work hope it's not a Flipping Tables issue

**Comment by Kangmo** [comment]
Thx, boudeffa~ ;-)

**Comment by nazimboudeffa** [comment]
i don't know here btw, :+1:

**Comment by Kangmo** [comment]
Closing, API layer implementation is already done.
