### ISSUE TITLE
Redesign CoinAddress isvalid module

### ISSUE THREAD

**Issue by mjpark03** [ScaleChain/scalachain#17]
# What
- Redesign CoinAddress isvalid module
# Why
- 'isvalid module' needs base58 and sha256
- now, use Base58Util and Sha256Util in util layer
- but, HashFunction exists in crypto layer
# How
- modify wallet layer dependency (add crypto layer) to remove Sha256Util in util layer
- or, maintain current version

**Comment by mjpark03** [comment]
decide to move HashUtil and Base58Util to crypto layer

**Comment by Kangmo** [comment]
Closing.
