### ISSUE TITLE
sbt test fails

### ISSUE THREAD

**Issue by sanxiyn** [ScaleChain/scalachain#2]
`sbt test` fails with:

```
[info] BlockDirectoryReaderSpec:
[info] readFrom
[info] - should read all blocks in a file *** FAILED ***
[info]   java.lang.NullPointerException:
```

Looking at the test, the test refers to the hardcoded path `/Users/kangmo`. It seems it should be replaced with a relative path?

**Comment by Kangmo** [comment]
Hi sanxiyn, thanks for opening the issue. I will fix this issue by using relative path instead of the full path starting with /Users/kangmo.

**Comment by Kangmo** [comment]
Removed the full path to a relative path. Commit done on the master branch. Could you verify if the sbt test command passes?

**Comment by sanxiyn** [comment]
Verified fixed.
