### ISSUE TITLE
Design details for Wallet, Account and CoinAddress

### ISSUE THREAD

**Issue by mjpark03** [ScaleChain/scalachain#20]
# What
- Design details for Wallet, Account and CoinAddress
# Why
- Need to implement RPCs related to wallet
- Current version is not designed for relationship
# How
- Analyze the relationship of Wallet, Account and CoinAddress
- Design details and Make design documents
- Implement the relationship of Wallet, Account and CoinAddress

**Comment by mjpark03** [comment]
- Wallet actions
  - Load: 
    load data from wallet.dat
  - Process: 
    manage key pairs of addresses
    manage transactions of addresses
    manage account
    manage key pool(new public and private keys pre-generated and stored in a queue)
  - Finish: 
    backup to wallet.dat

**Comment by Kangmo** [comment]
Closing, wallet layer is implemented.
