### ISSUE TITLE
Wallet RPCs Planning

### ISSUE THREAD

**Issue by mjpark03** [ScaleChain/scalachain#22]
# Analysis
1. analyze wallet.dat
   - output: wallet-format-analysis.md
2. analyze requirements for wallet RPCs
   - output: sequence diagram & summary of requirements documents
3. analyze BlockDatabase 
4. prototype WalletDatabase
# Design
1. design wallet architecture
   - output: architecture documents & rocksdb schema
2. design wallet RPCs
   - output: sequence diagram & module design documents
# Implement
1. implement wallet database (test cases & production code)
2. implement wallet PRCs (test cases & production code)

**Comment by mjpark03** [comment]
In-progress : analyze wallet.dat

**Comment by Kangmo** [comment]
Thx for updating your status. Keep going.

**Comment by mjpark03** [comment]
Done: analyze bitcoin core wallet.dat

https://github.com/ScaleChain/scalechain/commit/df78c8d9479820043e0c844edd11e72abf63551c

**Comment by mjpark03** [comment]
In-progress : analyze requirements for wallet RPCs

**Comment by mjpark03** [comment]
Done: analyze requirements for wallet RPCs

To-do: create sequence diagram in detail in design step
- getnewaddress RPC

<img width="683" alt="2016-03-14 9 45 32" src="https://cloud.githubusercontent.com/assets/5056158/13744870/1cc331f8-ea2e-11e5-8803-28f6a86e311d.png">
- getaccount RPC

<img width="692" alt="2016-03-14 9 43 06" src="https://cloud.githubusercontent.com/assets/5056158/13744838/f5e23a3e-ea2d-11e5-976d-da11b1cf7086.png">
- getaccountaddress RPC

<img width="689" alt="2016-03-14 9 43 28" src="https://cloud.githubusercontent.com/assets/5056158/13744879/2d687162-ea2e-11e5-98c0-2792e2a89960.png">
- getreceivedbyaddress RPC

<img width="691" alt="2016-03-14 9 43 40" src="https://cloud.githubusercontent.com/assets/5056158/13744899/4913b138-ea2e-11e5-9967-3a5740d662dc.png">
- listtransactions RPC

<img width="649" alt="2016-03-14 9 43 59" src="https://cloud.githubusercontent.com/assets/5056158/13744910/5e7ce594-ea2e-11e5-844b-4a5bb34f94f1.png">
- sendfrom RPC

<img width="644" alt="2016-03-14 9 44 11" src="https://cloud.githubusercontent.com/assets/5056158/13744920/73ed6174-ea2e-11e5-92fb-bf2a2e24c125.png">
- listunspent RPC

<img width="632" alt="2016-03-14 9 44 19" src="https://cloud.githubusercontent.com/assets/5056158/13744933/875c5620-ea2e-11e5-92e6-5ff3f45ce270.png">

**Comment by mjpark03** [comment]
In-progress: analyze BlockDatabase

**Comment by mjpark03** [comment]
prototype to 
1. use rocksdb
2. define codec
3. read data from .hex file

prototype result: https://github.com/ScaleChain/scalechain/commit/517427bbefb363309794ac7a7773d64edc955367

**Comment by mjpark03** [comment]
In-progress: prototype WalletDatabase

**Comment by mjpark03** [comment]
prototype WalletDatabase for putting and getting wallet info.
WalletInfo format is just test format.

prototype result: https://github.com/ScaleChain/scalechain/commit/5cca65461c51eab8e421cf518f1c7f7bef586e27

**Comment by mjpark03** [comment]
overall flow of using rocksdb and scodec

![fullsizerender](https://cloud.githubusercontent.com/assets/5056158/13769140/8f3a0fa8-eac0-11e5-85f0-525f60dfa715.jpg)

**Comment by mjpark03** [comment]
prototype wallet codecs for getting list

prototype result: https://github.com/ScaleChain/scalechain/commit/d8f6c32c1369e0ffda6b8da940e362bb78125831

**Comment by mjpark03** [comment]
Done: analyze BlockDatabase & prototype WalletDatabase

**Comment by mjpark03** [comment]
In-progress: design wallet architecture

**Comment by mjpark03** [comment]
In-progress: implement wallet database (test cases & production code)

**Comment by Kangmo** [comment]
Closing.
