### ISSUE TITLE
What is a Block ?

### ISSUE THREAD

**Issue by nazimboudeffa** [ScaleChain/scalachain#23]
14:25don1ruillis a block equal to a bitcoin ?
14:26don1ruillif there is two parts doing a transaction, and the transaction is about a certain amout of bitcoin
14:27don1ruillmeans a block is a function of bitcoins
14:27don1ruillthen a hash is affected to a transaction
14:28don1ruillan then define what is a hash for a bitcoin

**Comment by Kangmo** [comment]
Hi boudeffa, the issue system is for tracking issues on this project.
I will close this issue.
