### ISSUE TITLE
Installation with IntelliJ IDEA

### ISSUE THREAD

**Issue by nazimboudeffa** [ScaleChain/scalachain#24]
Hi,
Excuse me for the last comments i have done, it was a little bit complicated to understand this technology. So, after a while i have started to try the code with IntelliJ IDEA, and here are some screenshots

http://imgur.com/CWft3Y0
http://imgur.com/u2CdzrX
http://imgur.com/ESa3Zxx

After asking for JDK, i use 1.7
Then Scala SDK it has downloaded it automatically

Now i am in the phase of compilation, 
edit configuration 
click + 
then sbt task 
then apply
then run

**Comment by nazimboudeffa** [comment]
Here are some docs about my installation :+1: 
i'll add log files that are generated after clicking on RUN
https://www.dropbox.com/sh/rdl5si683iam6sm/AACRcOuRhx05qEU6KNGp8KSJa?dl=0

**Comment by Kangmo** [comment]
Hi boudeffa,

Please open an issue only if you find a bug in the code in this repository.

Thanks,
Kangmo
