### ISSUE TITLE
Prototype using embedded Cassandra for block storage.

### ISSUE THREAD

**Issue by Kangmo** [ScaleChain/scalachain#37]
## what

Prototype using embedded Cassandra for block storage.
## why

To see if Cassandra is a good option for the block storage.
## how
1. Implement KeyValueDatabase trait using Cassandra. 
2. Do not create a separate Cassandra process, but embed it with ScaleChian.

**Comment by Kangmo** [comment]
## Reference

### Embedding Cassandra

https://github.com/jsevellec/cassandra-unit/wiki/How-to-use-it-in-your-code
https://github.com/doanduyhai/Achilles

### Consistency level

http://docs.datastax.com/en/cassandra/2.0/cassandra/dml/dml_config_consistency_c.html

### Ordered UUIDs (time-based)

http://wiki.apache.org/cassandra/TimeBaseUUIDNotes

### Cassandra Java Driver

http://docs.datastax.com/en/latest-java-driver/java-driver/whatsNew2.html

### Connecting to Cassandra

http://docs.datastax.com/en/latest-java-driver/java-driver/quick_start/qsSimpleClientCreate_t.html

### CQL basics

http://docs.datastax.com/en/latest-java-driver/java-driver/quick_start/qsSimpleClientAddSession_t.html

### Bound statements

http://docs.datastax.com/en/latest-java-driver/java-driver/quick_start/qsSimpleClientBoundStatements_t.html

### Example of prepared statements

http://docs.datastax.com/en/latest-java-driver/java-driver/reference/javaClass2Cql3Datatypes.html?scroll=cql-java-types

### Simple Recipe for Phantom ( from b0c1)

https://github.com/outworkers/phantom/blob/develop/phantom-example/src/main/scala/com/websudos/phantom/example/basics/SimpleRecipes.scala

### Use cases : Financial sector

http://www.planetcassandra.org/blog/industry_use_cases/finance/

**Comment by Kangmo** [comment]
## In-progress : Implement CassandraDatabase, which extends from KeyValueDatabase.

## Why
1. We will use CassandraDatabase instead of BlockDatabase and RecordStorage to implement CassandraBlockStorage, which has the same interface with DiskBlockStorage.
2. To investigate if block data distribution using Cassandra is feasible.

## How
1. Start Cassandra in embedded to ScaleChain JVM process.
2. Create a table with key(primary key, blob) and value(blob)
3. Use prepared statements to implement put/get/del
   http://docs.datastax.com/en/latest-java-driver/java-driver/reference/javaClass2Cql3Datatypes.html?scroll=cql-java-types
4. Write automated test cases.

**Comment by b0c1** [comment]
Maybe you can try http://outworkers.github.io/phantom/ scala driver instead of native java :)

**Comment by Kangmo** [comment]
## Why Cassandra

### Support for CQL

It is like SQL, and my customer wants to use _something_ like SQL.

### Basically AP, but can choose CP. (among CAP)

I have to be able to choose CP to consistently write data even with multiple peers.

### No single point of failure.

No master nodes, no zookeeper, etc. Cassandra is a pure Peer to Peer system.

### Developed since 2008

It is developed since 2008, should have fixed lots of bugs, (maybe;-))

### Has references.

I need to sell this software to financial companies. So I need some database tech which is already deployed on financial companies.
http://www.planetcassandra.org/blog/industry_use_cases/finance/

### Has triggers

We need to verify if a data modification is not from a malicious node.
To make sure block header hash matches the one we expect, we need to verify data before it is modified. We will install triggers for each key/value table. Ex> block table will have a trigger to check if the block header hash matches the block header, and the merkle root hash matches the transactions in the block.
https://docs.datastax.com/en/cql/3.1/cql/cql_reference/trigger_r.html

**Comment by Kangmo** [comment]
## Won't use phantom.

Phantom is free but I can't re-distribute it. ;-)
https://github.com/outworkers/phantom/issues/317

alexflav23 commented on Sep 5, 2015
Hi @jtjeferreira,

None of our code is open source, it's just free to use. You can not re-distribute it, offer paid support for it or anything like that or you are in breach of license. The code for diesel is not public as of yet and only a very small part of it is available for free wide spread consumption.

**Comment by Kangmo** [comment]
Code Pushed : a28a8e1

**Comment by Kangmo** [comment]
Code pushed : 73760e3bc52957393f8abde9e5328ed8c407aed1

**Comment by Kangmo** [comment]
## In-progress : Add CassandraBlockStorage

Add CassandraBlockStorage, which can store blocks on Cassandra, instead of RecordStorage and BlockDatabase.

## Why

We will store blockchain data on (distributed) Cassandra. The Cassandra will be embedded into ScaleChain, so we don't need to start a separate process for it, but we will have to make sure that malicious nodes or hackers are not able to mutate Cassandra database.

## How
1. Extract methods required for RecordStorage from BlockDatabase into BlockDatabaseForRecordStorage
2. Create BlockStorage trait from DiskBlockStorage methods.
3. Create CassandraBlockStorage extending from the BlockStorage trait.
4. Use BlockDatabase to implement CassandraBlockStorage, without using any RecordStorage, which stores block headers and blocks on local file system(w/ RocksDB)

**Comment by Kangmo** [comment]
CassandraBlockStorage passed all tests.
