### ISSUE TITLE
Transaction Layer : Add transaction signer

### ISSUE THREAD

**Issue by Kangmo** [ScaleChain/scalachain#57]
## What

Add a transaction signer that signs a transaction using private keys.
## Why

We need to sign each input of a transaction if we have a matching private key for an input.
## How

Use ECKey.doSign to sign each input of a transaction.

**Comment by wolfshtein** [comment]
:+1:

**Comment by Kangmo** [comment]
Tests passed for transaction signing w/ multi inputs.
